### ISSUE TITLE
Build error with Julia nightly on Windows

### ISSUE THREAD

**Issue by dpo** [osqp/OSQP.jl#111]
Hi. One of my dependencies installs OSQP.jl, but the build consistently fails on Windows with Julia nightly. Here's the log: https://github.com/JuliaSmoothOptimizers/RegularizedOptimization.jl/runs/6197332880?check_suite_focus=true#step:5:156

Any ideas?

Thanks.

**Comment by imciner2** [comment]
That looks odd. OSQP.jl should be using pre-compiled artifacts from OSQP_jll in version 0.6.1, and even then we actually aren't doing any "building" or OSQP anymore (just manually downloading the compiled binaries). So that looks to be an issue with the Julia packaging/environment rather than an OSQP issue.

**Comment by odow** [comment]
Seems like this was using an old version of OSQP.jl. Is it still a problem in v0.8.0?

**Comment by dpo** [comment]
no
